# Generated by Django 6.0 on 2025-12-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoldLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('purchaser_name', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('vin', models.CharField(max_length=17)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
