# Generated by Django 6.0 on 2025-12-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sold_cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('vin', models.CharField(max_length=17)),
                ('odometer', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='SoldLog',
        ),
    ]
