# Generated by Django 6.0 on 2025-12-14 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sold_cars', '0002_soldvehicle_delete_soldlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldVehicleExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('sold_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_expenses', to='sold_cars.soldvehicle')),
            ],
        ),
    ]
