# Generated by Django 6.0 on 2025-12-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sold_cars', '0003_soldvehicleexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldvehicle',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
