# Generated by Django 6.0 on 2025-12-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sold_cars', '0004_soldvehicle_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldvehicle',
            name='auction_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='soldvehicle',
            name='original_purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
