# Generated by Django 6.0 on 2025-12-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('vin', models.CharField(max_length=17)),
                ('sbs_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sbs_tax_collected', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sbs_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
