# Generated by Django 6.0 on 2025-12-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinventory',
            name='status',
            field=models.CharField(choices=[('READY', 'Ready for Sale'), ('SERVICE', 'In Service'), ('SOLD', 'Sold')], default='READY', max_length=20),
        ),
    ]
