# Generated by Django 6.0 on 2025-12-13 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_vehicleinventory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleinventory',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='vehicleinventory',
            name='total_expenses',
        ),
        migrations.CreateModel(
            name='VehicleExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='inventory.vehicleinventory')),
            ],
        ),
    ]
