# Generated by Django 6.0 on 2025-12-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_vehicleinventory_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleexpense',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
